Lenz patch
lancelafontaine/caproomster pull request #55
Opened 2017-03-27 05:48 UTC by MonsieurPetion

backend lock removed no more checking

2017-03-27 14:36 UTC, choitwao commented
I only reviewed syntax (based on my knowledge) and logic. For the back-end functionality teammates should look into it

2017-03-27 17:00 UTC, arekmano requested changes
fix merge conflicts

2017-03-27 17:00 UTC, arekmano commented on app/mapper/RoomMapper.py
> +def setRoom(roomId):
does nothin

2017-03-27 18:00 UTC, Taimoorrana1 commented
Please merge with master. It's affecting your code covearge

2017-03-27 19:34 UTC, ghost requested changes
You need to pull from Master into your branch.

2017-03-27 19:34 UTC, adriannadiaz commented on app/core/registry.py
>              return True
refactor and remove this useless function

2017-03-27 19:34 UTC, adriannadiaz commented on app/core/registry.py
> +    def endAction(self):
refactor and remove this useless function

2017-03-27 19:34 UTC, adriannadiaz commented on app/templates/add.html
> -          <div class="text-center">Warning: After you select the room, you have 2 minutes to complete your reservation.</div>
This file doesn't exist anymore since we have gotten rid of ALL the front-end. You need to sync your branch with Master.

2017-03-27 19:34 UTC, adriannadiaz commented on app/views.py
>  								return render_template(redirectTo, allowed = "You can only have a reservation that totals to 2 hours per day")
All this code has been rendered obsolete, please pull from Master

2017-03-28 16:12 UTC, MonsieurPetion commented on app/mapper/RoomMapper.py
> +def setRoom(roomId):
done

2017-03-29 18:25 UTC, lancelafontaine reviewed
You also have tons of HTML still in this branch, that were removed from master. Delete them from this branch please.

2017-03-29 18:25 UTC, lancelafontaine commented on app/core/registry.py
>              return True
I agree, you should remove this completely.

2017-03-29 18:25 UTC, lancelafontaine commented on app/core/registry.py
> +    def endAction(self):
I agree, you should remove this completely.

2017-03-29 18:25 UTC, lancelafontaine commented on app/core/room.py
> +<<<<<<< HEAD
@MonsieurPetion you have merge conflict artifacts here, there is no way this application or the tests are running on this branch.

2017-03-29 18:25 UTC, lancelafontaine commented on app/mapper/RoomMapper.py
>  def update(room,availability):
Should remove this, now that availability is gone.

2017-04-01 14:17 UTC, MonsieurPetion commented on app/mapper/RoomMapper.py
>  def update(room,availability):
done

2017-04-01 14:31 UTC, MonsieurPetion commented on app/templates/add.html
> -          <div class="text-center">Warning: After you select the room, you have 2 minutes to complete your reservation.</div>
add.html does not exist anymore @adriannadiaz ??

2017-04-01 14:32 UTC, MonsieurPetion commented on app/views.py
>  								return render_template(redirectTo, allowed = "You can only have a reservation that totals to 2 hours per day")
done

2017-04-01 23:19 UTC, closed without merging