Fixes the failing tests on master, leftover Room lock constructors fr…
lancelafontaine/caproomster pull request #67
Opened 2017-04-01 19:46 UTC by lancelafontaine

…om my tests

2017-04-01 20:22 UTC, ghost requested changes
I am blocking the merge for this PR.
😛 
 Yes I will incorporate this fix, but there are WAY more tests broken in Master ATM. I am fixing all of them...

2017-04-01 20:24 UTC, adriannadiaz commented on app/views_test.py
>                  time = Timeslot(1, 2, '2020-01-01', '', 1, 1)
For example this Timeslot is invalid, since you know have strings for IDs, so the last parameter is invalid..

The integer 1 cannot be a UUID...

2017-04-01 20:24 UTC, adriannadiaz commented on app/views_test.py
>                  time = Timeslot(1, 2, '2020-01-01', '', 1, 1)
And here... Now I hope you get an idea why I have been stuck for over 2 hours trying to fix all the tests... LOL

2017-04-01 20:24 UTC, adriannadiaz commented
@lancelafontaine

2017-04-01 20:26 UTC, lancelafontaine commented
@adriannadiaz 

These are only for the tests. It accepts `1`, because these tests never reach the DB (they are being mocked), and `1` is technically a unique identifier,

You can change them if you like, but it does not change anything.

2017-04-02 01:33 UTC, ghost approved these changes

2017-04-02 01:33 UTC, merged